  $(document).ready(function(){
    $('#icon1').click(function(){
      $('#IO').show();
  });
  $('#icon1').click(function(){
    $('#icon1').hide();
});
$('#IO').click(function(){
  $('#icon1').show();
});
$('#IO').click(function(){
  $('#IO').hide();
});
  });
