  $(document).ready(function(){
    $('#design1').click(function(){
      $('#IO').show();
  });
  $('#design1').click(function(){
    $('#design1').hide();
});
$('#IO').click(function(){
  $('#design1').show();
});
$('#IO').click(function(){
  $('#IO').hide();
});
$('#design2').click(function(){
  $('#IP').show();
});
$('#design2').click(function(){
$('#design2').hide();
});
$('#IP').click(function(){
$('#design2').show();
});
$('#IP').click(function(){
$('#IP').hide();
});
$('#design3').click(function(){
  $('#IQ').show();
});
$('#design3').click(function(){
$('#design3').hide();
});
$('#IQ').click(function(){
$('#design3').show();
});
$('#IQ').click(function(){
$('#IQ').hide();
});
  });
