  $(document).ready(function(){
    $('#design1').click(function(){
      $('#IO').show();
  });
  $('#design1').click(function(){
    $('#design1').hide();
});
$('#IO').click(function(){
  $('#design1').show();
});
$('#IO').click(function(){
  $('#IO').hide();
});
$('#design2').click(function(){
  $('#IP').show();
});
$('#design2').click(function(){
$('#design2').hide();
});
$('#IP').click(function(){
$('#design2').show();
});
$('#IP').click(function(){
$('#IP').hide();
});
$('#design3').click(function(){
  $('#IQ').show();
});
$('#design3').click(function(){
$('#design3').hide();
});
$('#IQ').click(function(){
$('#design3').show();
});
$('#IQ').click(function(){
$('#IQ').hide();
});




$(".x1").mouseenter(function(){
$(".y1").show(500);
});
$(".x1").mouseleave(function(){
$(".y1").hide(1000);
});
$(".x2").mouseenter(function(){
$(".y2").show(500);
});
$(".x2").mouseleave(function(){
$(".y2").hide(1000);
});
$(".x3").mouseenter(function(){
$(".y3").show(500);
});
$(".x3").mouseleave(function(){
$(".y3").hide(1000);
});
$(".x4").mouseenter(function(){
$(".y4").show(500);
});
$(".x4").mouseleave(function(){
$(".y4").hide(1000);
});
$(".x5").mouseenter(function(){
$(".y5").show(500);
});
$(".x5").mouseleave(function(){
$(".y5").hide(1000);
});
$(".x6").mouseenter(function(){
$(".y6").show(500);
});
$(".x6").mouseleave(function(){
$(".y6").hide(1000);
});
$(".x7").mouseenter(function(){
$(".y7").show(500);
});
$(".x7").mouseleave(function(){
$(".y7").hide(1000);
});
$(".x8").mouseenter(function(){
  $(".y8").show(500);
});
$(".x8").mouseleave(function(){
  $(".y8").hide(1000);
});
  });


